# Workflow for applying changes from the main branch to github pages
name: pages-main

on:
  # Runs on pushes and pull requests targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Prevent race conditions between main and preview deploys by setting the same
# concurrency group and forcing them to queue.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Add changes from main to the gh-pages branch and commit
  update-from-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy contents to subdirectory
        run: |
          echo "Copying contents to main/"
          cp -rT . ../main/
          rm -r ../main/.git
      - name: Checkout gh-pages branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin -a
          git checkout gh-pages
      - name: Commit changes from main
        run: |
          yes | cp -rT ../main .
          rm -rf main
          git add .
          git commit -m "Update from main" -m "${{ github.sha }}"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
