# Workflow for building and deploying PRs to preview changes on github pages
name: pages-preview-remove

on:
  # Runs on closed pull requests targeting the default branch that change HTML or CSS
  pull_request:
    branches: ["main"]
    types: ["closed"]
    paths:
      - "**/*.html"
      - "**/*.css"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Prevent race conditions between main and preview deploys by setting the same
# concurrency group and forcing them to queue.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  # Name of the directory where the preview will be built
  PREVIEW_DIR: preview-${{ github.event.number }}

jobs:
  # When the PR is closed, remove the preview directory
  remove-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout gh-pages branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin -a
          git checkout gh-pages
      - name: Delete preview directory
        run: |
          git rm -r $PREVIEW_DIR
          git commit -m "Remove preview for PR ${{ github.event.number }}"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
