# Workflow for building and deploying the main branch to github pages
name: pages-main

on:
  # Runs on pushes and pull requests targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Prevent race conditions between main and preview deploys by setting the same
# concurrency group and forcing them to queue.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build site and commit to gh-pages branch
  build-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Update gh-pages branch from main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin -a
          git checkout main
          git checkout gh-pages
          git merge -s theirs main
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
